spring.application.name=app_universitaria
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:app_universitaria}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.data-locations=classpath:db/seed_unsada_prioritarios_2026.sql

logging.level.org.hibernate.SQL=${LOG_LEVEL_HIBERNATE_SQL:INFO}
logging.level.org.hibernate.orm.jdbc.bind=${LOG_LEVEL_HIBERNATE_BIND:INFO}
logging.level.com.appuniversitaria=${LOG_LEVEL_APP:INFO}
logging.level.org.springframework.web=${LOG_LEVEL_WEB:INFO}
server.port=${SERVER_PORT:8081}
